import type { PoliticalParty } from '@/types/parties';

export const POLITICAL_PARTIES: PoliticalParty[] = [
  {
    id: 'aap',
    name: 'AAP',
    fullName: 'Aam Aadmi Party',
    imagePath: '/logos-loop/aap-logo.png',
    color: '#00BFFF',
    website: 'https://www.aamaadmiparty.org/',
  },
  {
    id: 'bjp',
    name: 'BJP',
    fullName: 'Bharatiya Janata Party',
    imagePath: '/logos-loop/bjp-logo.png',
    color: '#FF9933',
    website: 'https://www.bjp.org/',
  },
  {
    id: 'bsp',
    name: 'BSP',
    fullName: 'Bahujan Samaj Party',
    imagePath: '/logos-loop/bsp-logo.png',
    color: '#0000FF',
    website: 'https://www.bspindia.org/',
  },
  {
    id: 'cpi',
    name: 'CPI',
    fullName: 'Communist Party of India',
    imagePath: '/logos-loop/cpi-logo.png',
    color: '#FF0000',
    website: 'https://www.communistparty.in/',
  },
  {
    id: 'dmk',
    name: 'DMK',
    fullName: 'Dravida Munnetra Kazhagam',
    imagePath: '/logos-loop/dmk-logo.png',
    color: '#FF0000',
    website: 'https://www.dmk.in/',
  },
  {
    id: 'inc',
    name: 'INC',
    fullName: 'Indian National Congress',
    imagePath: '/logos-loop/inc-logo.png',
    color: '#00BFFF',
    website: 'https://www.inc.in/',
  },
  {
    id: 'jdu',
    name: 'JDU',
    fullName: 'Janata Dal (United)',
    imagePath: '/logos-loop/jdu-logo.png',
    color: '#008000',
    website: 'https://www.jdunited.in/',
  },
  {
    id: 'ncp',
    name: 'NCP',
    fullName: 'Nationalist Congress Party',
    imagePath: '/logos-loop/ncp-logo.png',
    color: '#00008B',
    website: 'https://www.ncp.org.in/',
  },
  {
    id: 'rjd',
    name: 'RJD',
    fullName: 'Rashtriya Janata Dal',
    imagePath: '/logos-loop/rjd-logo.png',
    color: '#0000FF',
    website: 'https://www.rjd.in/',
  },
  {
    id: 'sp',
    name: 'SP',
    fullName: 'Samajwadi Party',
    imagePath: '/logos-loop/sp-logo.png',
    color: '#00BFFF',
    website: 'https://www.samajwadiparty.in/',
  },
  {
    id: 'tmc',
    name: 'TMC',
    fullName: 'Trinamool Congress',
    imagePath: '/logos-loop/tmc-logo.png',
    color: '#008000',
    website: 'https://www.tmc.org.in/',
  },
  {
    id: 'tvk',
    name: 'TVK',
    fullName: 'Tamilaga Vettri Kazhagam',
    imagePath: '/logos-loop/tvk-logo.png',
    color: '#FF0000',
    website: '',
  },
];

export default POLITICAL_PARTIES;